apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.env}}-quotes-microservice-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tags.datadoghq.com/env: myenv
    tags.datadoghq.com/service: quotes-microservice
    tags.datadoghq.com/version: "1"
    admission.datadoghq.com/enabled: "true"
spec:
  selector:
    matchLabels:
      app: "{{.Values.env}}-quotes-microservice-deployment"
  replicas: {{ default 1 .Values.deployment.replicas | int }}
  template:
    metadata:
      labels:
        app: "{{.Values.env}}-quotes-microservice-deployment"
        admission.datadoghq.com/enabled: "true"
      annotations:
        prometheus.io/port: "{{ .Values.http.containerPort }}"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        admission.datadoghq.com/nodejs-lib.version: v3.11.0
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{.Values.image.tag}}"
        env:
          - name: DATABASE_PREFIX
            value: mongodb
          - name: DATABASE_USER
            value: admin
          - name: DATABASE_PASSWORD
            value: admin
          - name: DATABASE_HOST
            value: "{{.Values.env}}-quotes-mongodb.{{.Values.env}}-databases-namespace"
          - name: DATABASE_NAME
            value: quotes-db
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_TRACE_STARTUP_LOGS
            value: "true"

        ports:
        - containerPort: {{ .Values.http.containerPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}