apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.env}}-quotes-microservice-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{.Values.env}}-quotes-microservice-service"
spec:
  ports:
  - name: web
    port: {{ .Values.http.port }}
    targetPort: {{ .Values.http.containerPort }}
    protocol: TCP
  selector:
    app: "{{.Values.env}}-quotes-microservice-deployment"