apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.env}}-quotes-microservice-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: "{{.Values.env}}-quotes-microservice-deployment"
  replicas: {{ default 1 .Values.deployment.replicas | int }}
  template:
    metadata:
      labels:
        app: "{{.Values.env}}-quotes-microservice-deployment"
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{.Values.image.tag}}"
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_PREFIX
            value: mongodb
          - name: DATABASE_USER
            value: admin
          - name: DATABASE_PASSWORD
            value: admin
          - name: DATABASE_HOST
            value: "{{.Values.env}}-quotes-mongodb.{{.Values.env}}-databases-namespace"
          - name: DATABASE_NAME
            value: quotes-db
        ports:
        - containerPort: {{ .Values.http.containerPort | int }}
        resources:
{{ toYaml .Values.resources | indent 10 }}