apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.Values.env}}-quotes-microservice"
spec:
  destination:
    namespace: "{{.Values.env}}-microservices-namespace"
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure/chart
    repoURL: 'https://github.com/Saief1999/quotes-explorer'
    targetRevision: HEAD
    helm:
      releaseName: mychart
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
