apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-microservice
spec:
  destination:
    name: ''
    namespace: dev-microservices-namespace
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure/chart
    repoURL: 'https://github.com/Saief1999/quotes-explorer'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
